baseURL = "http://mehthehedgehog.github.io/"
languageCode = "en-us"
title = "MehTheHedgehog's Blog"
theme = "hedgehog"
publishDir = "docs"

[Author]
    name = "Artur Jaworski"
    describtion = "Software developer from Poland."

[Social]
    facebookuid = "100000560180331"
