# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hedgehog"
license = "MIT"
licenselink = "https://github.com/MehTheHedgehog/mehthehedgehog.github.io/blob/sources/README.md"
description = "Programing blog under github.io"
homepage = "https://github.com/MehTheHedgehog/mehthehedgehog.github.io"
tags = []
features = []
min_version = "0.20"

[author]
  name = "MehTheHedgehog"
  homepage = "https://github.com/MehTheHedgehog/mehthehedgehog.github.io"
